# Configuration/Services.yaml
services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  BalatD\FriendlyCaptcha\:
    resource: '../Classes/*'

  BalatD\FriendlyCaptcha\Services\FriendlyCaptchaService:
    arguments:
      - '@TYPO3\CMS\Extbase\Configuration\ConfigurationManager'
      - '@TYPO3\CMS\Core\TypoScript\TypoScriptService'
      - '@TYPO3\CMS\Frontend\ContentObject\ContentObjectRenderer'
    public: true

  BalatD\FriendlyCaptcha\Adapter\SfRegisterAdapter:
    public: true
